import React from 'react'
import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import AboutPage from '../components/AboutPage'

const about = () => {
  return (
    <div>
      <Head>
        <title>
          Dinma's Portfolio
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <AboutPage/>
      </Box>

    </div>
  )
}

export default about
