import React from 'react'
import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import AboutPage from '../components/AboutPage'
import Project from '../components/PortfolioPage'
import { getRepositories } from '../utils/services'

const portfolio = ({repositories}) => {

   
  return (
    <div>
      <Head>
        <title>
          Dinma's Portfolio
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Project repositories={repositories}></Project>
      </Box>

    </div>
  )
}

export async function getServerSideProps() {
    const repositories = await getRepositories();

    return {
      props: {
        repositories
      },
    };
  }

export default portfolio
